name: Dependabot Tests

on:
  create: # Trigger the workflow when a new branch is created

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' # Run this job only if the actor is Dependabot

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cache pipenv dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.local/share/virtualenvs
          .venv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Run tests
      run: |
        pipenv run python -m unittest discover -s tests
